--------------------------------------------------------
-- Archivo creado  - domingo-enero-29-2017   
--------------------------------------------------------
DROP TABLE "ENC_PRE" cascade constraints;
DROP TABLE "ENCUESTA" cascade constraints;
DROP TABLE "ENVIO" cascade constraints;
DROP TABLE "OPCION" cascade constraints;
DROP TABLE "PREGUNTA" cascade constraints;
DROP TABLE "PROYECTO" cascade constraints;
DROP TABLE "RESPUESTA" cascade constraints;
DROP SEQUENCE "ENCUESTA_SEQ";
DROP SEQUENCE "ENVIO_SEQ";
DROP SEQUENCE "OPCION_SEQ";
DROP SEQUENCE "PREGUNTA_SEQ";
DROP SEQUENCE "PROYECTO_SEQ";
DROP SEQUENCE "RESPUESTA_SEQ";
DROP VIEW "RESPUESTA_ENCUESTA";
DROP VIEW "RESPUESTA_EVALUACION";
--------------------------------------------------------
--  DDL for Sequence ENCUESTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ENCUESTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ENVIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ENVIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OPCION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "OPCION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PREGUNTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREGUNTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROYECTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RESPUESTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RESPUESTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ENC_PRE
--------------------------------------------------------

  CREATE TABLE "ENC_PRE" 
   (	"IDENCUESTA" NUMBER(*,0), 
	"IDPREGUNTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENCUESTA
--------------------------------------------------------

  CREATE TABLE "ENCUESTA" 
   (	"IDENCUESTA" NUMBER(*,0), 
	"ENCUESTA" VARCHAR2(50 BYTE), 
	"TITULO" VARCHAR2(250 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"TIPOENCUESTA" CHAR(1 BYTE), 
	"ESTADO" CHAR(1 BYTE), 
	"USUARIOCREADOR" VARCHAR2(50 BYTE), 
	"FECHACREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENVIO
--------------------------------------------------------

  CREATE TABLE "ENVIO" 
   (	"IDENVIO" NUMBER(*,0), 
	"FECHAENVIO" DATE, 
	"USUARIOCREADOR" VARCHAR2(50 BYTE), 
	"DESTINATARIO" VARCHAR2(100 BYTE), 
	"ESTADO" CHAR(1 BYTE), 
	"FKENCUESTA" NUMBER(*,0), 
	"FKPROYECTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OPCION
--------------------------------------------------------

  CREATE TABLE "OPCION" 
   (	"IDOPCION" NUMBER(*,0), 
	"OPCION" VARCHAR2(250 BYTE), 
	"VALOR" FLOAT(126), 
	"FKPREGUNTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTA
--------------------------------------------------------

  CREATE TABLE "PREGUNTA" 
   (	"IDPREGUNTA" NUMBER(*,0), 
	"TITULO" VARCHAR2(250 BYTE), 
	"AYUDA" VARCHAR2(250 BYTE), 
	"TIPOPREGUNTA" VARCHAR2(50 BYTE), 
	"TIPOENCUESTA" CHAR(1 BYTE), 
	"ESTADO" CHAR(1 BYTE), 
	"ESCALAVALORACION" NUMBER(2,0), 
	"USUARIOCREADOR" VARCHAR2(50 BYTE), 
	"FECHACREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROYECTO
--------------------------------------------------------

  CREATE TABLE "PROYECTO" 
   (	"IDPROYECTO" NUMBER(*,0), 
	"PROYECTO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "RESPUESTA" 
   (	"IDRESPUESTA" NUMBER(*,0), 
	"OBSERVACION" VARCHAR2(500 BYTE), 
	"VALORACION" NUMBER(2,0), 
	"USUARIOEVALUADO" VARCHAR2(50 BYTE), 
	"FKPREGUNTA" NUMBER(*,0), 
	"FKOPCION" NUMBER(*,0), 
	"FKENVIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENCUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENCUESTA_PK" ON "ENCUESTA" ("IDENCUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OPCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OPCION_PK" ON "OPCION" ("IDOPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREGUNTA_PK" ON "PREGUNTA" ("IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENC_PRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENC_PRE_PK" ON "ENC_PRE" ("IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROYECTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO_PK" ON "PROYECTO" ("IDPROYECTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESPUESTA_PK" ON "RESPUESTA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENVIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENVIO_PK" ON "ENVIO" ("IDENVIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "OPCION" MODIFY ("FKPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "OPCION" ADD CONSTRAINT "OPCION_PK" PRIMARY KEY ("IDOPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OPCION" MODIFY ("OPCION" NOT NULL ENABLE);
  ALTER TABLE "OPCION" MODIFY ("IDOPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROYECTO
--------------------------------------------------------

  ALTER TABLE "PROYECTO" ADD CONSTRAINT "PROYECTO_PK" PRIMARY KEY ("IDPROYECTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROYECTO" MODIFY ("PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO" MODIFY ("IDPROYECTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENVIO
--------------------------------------------------------

  ALTER TABLE "ENVIO" ADD CONSTRAINT "ENV_ESTADO_CHECK" CHECK (estado IN ('P', 'R')) ENABLE;
  ALTER TABLE "ENVIO" MODIFY ("FKENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "ENVIO" ADD CONSTRAINT "ENVIO_PK" PRIMARY KEY ("IDENVIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ENVIO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ENVIO" MODIFY ("DESTINATARIO" NOT NULL ENABLE);
  ALTER TABLE "ENVIO" MODIFY ("USUARIOCREADOR" NOT NULL ENABLE);
  ALTER TABLE "ENVIO" MODIFY ("FECHAENVIO" NOT NULL ENABLE);
  ALTER TABLE "ENVIO" MODIFY ("IDENVIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENCUESTA
--------------------------------------------------------

  ALTER TABLE "ENCUESTA" ADD CONSTRAINT "ENC_ESTADO_CHECK" CHECK (estado IN ('A', 'I')) ENABLE;
  ALTER TABLE "ENCUESTA" ADD CONSTRAINT "ENC_TIPOENCUESTA_CHECK" CHECK (tipoEncuesta IN ('N', 'E')) ENABLE;
  ALTER TABLE "ENCUESTA" ADD CONSTRAINT "ENCUESTA_PK" PRIMARY KEY ("IDENCUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ENCUESTA" MODIFY ("FECHACREACION" NOT NULL ENABLE);
  ALTER TABLE "ENCUESTA" MODIFY ("USUARIOCREADOR" NOT NULL ENABLE);
  ALTER TABLE "ENCUESTA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ENCUESTA" MODIFY ("TIPOENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "ENCUESTA" MODIFY ("ENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "ENCUESTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "PREGUNTA" ADD CONSTRAINT "PRE_TIPOENCUESTA_CHECK" CHECK (tipoEncuesta IN ('N', 'E')) ENABLE;
  ALTER TABLE "PREGUNTA" ADD CONSTRAINT "PRE_TIPOPREGUNTA_CHECK" CHECK (tipoPregunta IN ('abierta', 'simple', 'ranking')) ENABLE;
  ALTER TABLE "PREGUNTA" ADD CONSTRAINT "PRE_ESTADO_CHECK" CHECK (estado IN ('A', 'I')) ENABLE;
  ALTER TABLE "PREGUNTA" ADD CONSTRAINT "PREGUNTA_PK" PRIMARY KEY ("IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PREGUNTA" MODIFY ("FECHACREACION" NOT NULL ENABLE);
  ALTER TABLE "PREGUNTA" MODIFY ("USUARIOCREADOR" NOT NULL ENABLE);
  ALTER TABLE "PREGUNTA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PREGUNTA" MODIFY ("TIPOENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "PREGUNTA" MODIFY ("TIPOPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "PREGUNTA" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "PREGUNTA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENC_PRE
--------------------------------------------------------

  ALTER TABLE "ENC_PRE" ADD CONSTRAINT "ENC_PRE_PK" PRIMARY KEY ("IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ENC_PRE" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "ENC_PRE" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "RESPUESTA" MODIFY ("FKENVIO" NOT NULL ENABLE);
  ALTER TABLE "RESPUESTA" MODIFY ("FKPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "RESPUESTA" ADD CONSTRAINT "RESPUESTA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "RESPUESTA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ENC_PRE
--------------------------------------------------------

  ALTER TABLE "ENC_PRE" ADD CONSTRAINT "EP_FKENCUESTA" FOREIGN KEY ("IDENCUESTA")
	  REFERENCES "ENCUESTA" ("IDENCUESTA") ENABLE;
  ALTER TABLE "ENC_PRE" ADD CONSTRAINT "EP_FKPREGUNTA" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENVIO
--------------------------------------------------------

  ALTER TABLE "ENVIO" ADD CONSTRAINT "ENV_FKENCUESTA" FOREIGN KEY ("FKENCUESTA")
	  REFERENCES "ENCUESTA" ("IDENCUESTA") ENABLE;
  ALTER TABLE "ENVIO" ADD CONSTRAINT "ENV_FKPROYECTO" FOREIGN KEY ("FKPROYECTO")
	  REFERENCES "PROYECTO" ("IDPROYECTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "OPCION" ADD CONSTRAINT "OPC_FKPREGUNTA" FOREIGN KEY ("FKPREGUNTA")
	  REFERENCES "PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "RESPUESTA" ADD CONSTRAINT "RES_FKENVIO" FOREIGN KEY ("FKENVIO")
	  REFERENCES "ENVIO" ("IDENVIO") ENABLE;
  ALTER TABLE "RESPUESTA" ADD CONSTRAINT "RES_FKOPCION" FOREIGN KEY ("FKOPCION")
	  REFERENCES "OPCION" ("IDOPCION") ENABLE;
  ALTER TABLE "RESPUESTA" ADD CONSTRAINT "RES_FKPREGUNTA" FOREIGN KEY ("FKPREGUNTA")
	  REFERENCES "PREGUNTA" ("IDPREGUNTA") ENABLE;
    --------------------------------------------------------
--  DDL for View RESPUESTA_ENCUESTA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RESPUESTA_ENCUESTA" ("IDRESPUESTA", "OBSERVACION", "VALORACION", "USUARIOEVALUADO", "IDPREGUNTA", "TITULO", "TIPOPREGUNTA", "TIPOENCUESTAPREG", "ESTADOPREG", "ESCALAVALORACION", "IDOPCION", "OPCION", "VALOR", "IDENVIO", "FECHAENVIO", "USUARIOCREADOR", "IDPROYECTO", "PROYECTO", "IDENCUESTA", "ENCUESTA", "TIPOENCUESTAENC", "ESTADOENC") AS 
  (
Select r.IDRESPUESTA, r.OBSERVACION, r.VALORACION, r.USUARIOEVALUADO, p.IDPREGUNTA, p.TITULO, p.TIPOPREGUNTA, p.TIPOENCUESTA as tipoEncuestaPreg, p.ESTADO as estadoPreg, p.ESCALAVALORACION, o.IDOPCION, o.OPCION, o.VALOR, en.IDENVIO, en.FECHAENVIO, en.USUARIOCREADOR, pro.IDPROYECTO, pro.PROYECTO, e.IDENCUESTA, e.ENCUESTA, e.TIPOENCUESTA as tipoEncuestaEnc, e.ESTADO as estadoEnc
from respuesta r join PREGUNTA p on r.FKPREGUNTA = p.IDPREGUNTA LEFT JOIN OPCION o on r.FKOPCION = o.IDOPCION join ENVIO en on r.FKENVIO = en.IDENVIO 
  join ENCUESTA e on en.FKENCUESTA = e.IDENCUESTA LEFT JOIN PROYECTO pro on en.FKPROYECTO = pro.IDPROYECTO
WHERE en.ESTADO = 'R');
--------------------------------------------------------
--  DDL for View RESPUESTA_EVALUACION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RESPUESTA_EVALUACION" ("IDRESPUESTA", "IDENVIO", "USUARIOEVALUADO", "FECHAENVIO", "IDENCUESTA", "ENCUESTA", "ESTADO", "FKPREGUNTA", "FKOPCION", "VALORR", "VALORACIONR", "VALORTOTALP", "VALORACIONTOTALP") AS 
  ( select r.idrespuesta, en.IDENVIO, r.USUARIOEVALUADO, en.FECHAENVIO, e.IDENCUESTA ,e.ENCUESTA, e.estado, r.FKPREGUNTA, r.FKOPCION, opr.VALOR as valorR ,r.VALORACION as valoracionR, totalpreguntas.valor as valorTotalP, totalpreguntas.valoracion as valoracionTotalP
from RESPUESTA r join ENVIO en on r.FKENVIO = en.IDENVIO join ENCUESTA E on en.FKENCUESTA = e.IDENCUESTA
  left join opcion opr on r.FKOPCION = opr.IDOPCION, (select  p.IDPREGUNTA as pregunta , max(o.VALOR) as valor, p.ESCALAVALORACION as valoracion from pregunta p left join opcion o on p.IDPREGUNTA = o.FKPREGUNTA
where p.TIPOENCUESTA = 'E' and p.TIPOPREGUNTA in ('simple', 'ranking') GROUP BY p.IDPREGUNTA , p.ESCALAVALORACION) totalpreguntas 
where e.TIPOENCUESTA = 'E' and totalpreguntas.pregunta = r.FKPREGUNTA );
