/*DROP SECUENCIAS*/

DROP SEQUENCE enc_pre_seq;
DROP SEQUENCE encuesta_seq;
DROP SEQUENCE envio_seq;
DROP SEQUENCE opcion_seq;
DROP SEQUENCE pregunta_seq;
DROP SEQUENCE proyecto_seq;
DROP SEQUENCE respuesta_seq;


/*DROP TABLAS*/

DROP TABLE ENC_PRE;
DROP TABLE ENCUESTA;
DROP TABLE ENVIO;
DROP TABLE OPCION;
DROP TABLE PREGUNTA;
DROP TABLE PROYECTO;
DROP TABLE RESPUESTA;

